import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import React from "react";
import { Providers } from "~/app/providers";
import MainNavbar from "~/app/_components/MainNavbar";
import SessionProvider from "~/app/_components/SessionProvider";
import { auth } from "auth";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { chefFileRouter } from "~/app/api/uploadthing/core";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Goose Chef",
  description: "Generated by create-t3-app",
  icons: [{ url: "/images/Logo_round_V2.png" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    //Currently there is no better solution than suppressing the error message: https://github.com/pacocoursey/next-themes/issues/169
    <html lang="en" suppressHydrationWarning>
      <body
        className={`font-sans ${inter.variable} min-h-screen bg-background  text-foreground`}
      >
        <NextSSRPlugin routerConfig={extractRouterConfig(chefFileRouter)} />
        <SessionProvider session={session}>
          <Providers>
            <MainNavbar />
            <TRPCReactProvider headers={headers()}>
              <div className="mx-auto max-w-screen-xl p-8">
                <Toaster />
                {children}
              </div>
            </TRPCReactProvider>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
