import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import React from "react";
import { Providers } from "~/app/providers";
import { getServerSession } from "next-auth";
import MainNavbar from "~/app/_components/MainNavbar";
import SessionProvider from "~/app/_components/SessionProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Goose Chef",
  description: "Generated by create-t3-app",
  icons: [{ url: "/images/Logo_round_V2.png" }],
};

export default async function RootLayout({
  children}: { children: React.ReactNode; }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} min-h-screen bg-background text-foreground`}
      >
        <SessionProvider session={session}>
          <Providers>
            <MainNavbar />
            <TRPCReactProvider headers={headers()}>
              <div className="mx-auto max-w-screen-xl p-8">{children}</div>
            </TRPCReactProvider>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
